// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package user_gql

type BaseUser struct {
	UUID     string `json:"uuid"`
	Username string `json:"username"`
	Role     string `json:"role"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	Role     string `json:"role"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUserInput struct {
	Username *string `json:"username,omitempty"`
	Role     *string `json:"role,omitempty"`
	Password *string `json:"password,omitempty"`
}

type UserPage struct {
	Users      []*BaseUser `json:"users"`
	TotalCount int         `json:"total_count"`
	Page       int         `json:"page"`
	PageSize   int         `json:"page_size"`
}
