// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package auth_gql

type CheckTokenInput struct {
	AccessToken string `json:"AccessToken"`
}

type CheckTokenResult struct {
	UUID     string `json:"UUID"`
	Username string `json:"Username"`
	Role     string `json:"Role"`
}

type LoginInput struct {
	Username string `json:"Username"`
	Password string `json:"Password"`
}

type LoginResult struct {
	AccessToken  string `json:"AccessToken"`
	RefreshToken string `json:"RefreshToken"`
}

type Mutation struct {
}

type Query struct {
}

type RefreshTokenInput struct {
	RefreshToken string `json:"RefreshToken"`
}

type RefreshTokenResult struct {
	AccessToken  string `json:"AccessToken"`
	RefreshToken string `json:"RefreshToken"`
}

type RegisterInput struct {
	Username string `json:"Username"`
	Password string `json:"Password"`
}

type RegisterResult struct {
	AccessToken  string `json:"AccessToken"`
	RefreshToken string `json:"RefreshToken"`
}
